### ISSUE TITLE
FPT source down!

### ISSUE THREAD

**Issue by anhstar** [zecoj/kodi-tvvn#2]
Hi, just want to inform you that the FPT's source is down once again.
This is what I have in the log: 
21:21:20 6132.255859 T:1430381600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 500: Internal Server Error
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.tvvn/tvvn.py", line 263, in <module>
                                                play_link(chn, src)
                                              File "/home/osmc/.kodi/addons/plugin.video.tvvn/tvvn.py", line 182, in play_link
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 437, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 475, in error
                                                return self._call_chain(_args)
                                              File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
                                                result = func(_args)
                                              File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 500: Internal Server Error
                                            -->End of Python script error report<--

Thanks

**Comment by zecoj** [comment]
Sorry for the very late reply. This won't be fixed as FPT has completely closed down publicly available channels.
